### ISSUE TITLE
The Explanation of the iCAN's implementation in tab. 4

### ISSUE THREAD

**Issue by ddwhzh** [enlighten0707/Body-Part-Map-for-Interactiveness#3]
I'm sorry to interrupt, but I noticed that the paper tab. 4 makes use of iCAN, and I'd like to ask about the implementation details.
Since the transformer-base methods use the Hungarian matching algorithm, how can the results of iCAN be introduced for assistance?
Also could you provide the corresponding code ideas, Thank you.

**Comment by enlighten0707** [comment]
The transformer-based methods use the Hungarian matching algorithm only for training, not testing. Instead, in our setting, iCAN is only used to evaluate the quality of the detected boxes in the _test_ set. 

To be specific: 
For the two-stage method iCAN, it is fed with {(b(h), b(o))}\_{i=1}^{N} for each image in the test set, and outputs {p_{hoi}}\_{i=1}^{N}. Here N is the number of candidate H-O pairs in the image, and b(h), b(o), p_{hoi} is human bbox, object bbox, hoi prediction.
Originally, {(b(h), b(o))}\_{i=1}^{N} is from Fast-RCNN detection and exhaustive pairing. In Tab.4, we replace it with the output of our one-stage method, and N is fixed as query size. In the implementation, we save the output of our models and feed it into iCAN via their open-source code.

For the results in Tab.4:
The performance is better than the original iCAN because of the improved quality of H-O pairing. It is worse than the one-stage method because iCAN is not exactly trained via one-stage DETR. However, with higher-quality H-O boxes, iCAN will perform better. Thus, it can measure the quality of one-stage H-O pairing.

Hope it helps.
