### ISSUE TITLE
Where is the checkpoint file, checkpoint_bst_binary.pth

### ISSUE THREAD

**Issue by MisakaZipi** [enlighten0707/Body-Part-Map-for-Interactiveness#6]
Hello author:

I tried to run your code for evaluating the HOI but found an error:

FileNotFoundError: [Errno 2] No such file or directory: './exp/interactiveness_train/checkpoint_bst_binary.pth'

Would you please tell me how can I download this file

Thank you very much.

**Comment by aparico** [comment]
@enlighten0707 I have the same problem too 🙏🏽

**Comment by enlighten0707** [comment]
We have uploaded the checkpoint in this [link](https://drive.google.com/drive/folders/1UydzhAbgsUG4jHK27Oi8m3vOF8pTtjz4?usp=share_link). You can put it into `./exp/bst_interactiveness/checkpoint_bst_binary.pth`.
Its binary AP is 38.19 since we are still working to clean up the code. 
I hope this helps you :)
